---
- name: Install sysctl settings
  ansible.builtin.template: src=sysctl.conf.j2 dest=/etc/sysctl.conf owner=root group=root mode=400

- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p /etc/sysctl.conf

- name: increase max number of File Descriptors for root
  community.general.pam_limits:
    domain: root
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: 'hard', limit_item: 'nofile', value: 65536 }
    - { limit_type: 'soft', limit_item: 'nofile', value: 65536 }

- name: increase max number of File Descriptors for *
  community.general.pam_limits:
    domain: "*"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: 'hard', limit_item: 'nofile', value: 65536 }
    - { limit_type: 'soft', limit_item: 'nofile', value: 65536 }
