---
# Arena MOTD which is required by AC-8 [GOV-6].
- name: Copy motd file
  ansible.builtin.copy:
    src: motd
    dest: /etc/update-motd.d/90-arena-banner
    mode: 0755
    owner: root
    group: root