---
- name: Install jq
  yum:
    name: jq
    state: latest

- name: Copy mount_storage_gateway.sh
  ansible.builtin.template:
    src: mount_storage_gateway.sh.j2
    dest: /tmp/mount_storage_gateway.sh
    owner: root
    group: root
    mode: 0755

- name: Mount the Storage Gateway
  ansible.builtin.shell: /tmp/mount_storage_gateway.sh