apiVersion: v1
kind: PersistentVolume
metadata:
   name: mypv
spec:
   accessModes:
        - ReadWriteMany
   storageClassName: normal
   capacity:
         storage: 2G
   hostPath:
         path: /opt
