apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name: mypvc
spec:
    storageClassName: normal
    accessModes:
         - ReadWriteMany
    resources:
          requests:
                  storage: 2G
